### PR TITLE
Unify modules and folders

### PR DESCRIPTION
**Pull request by soywiz**

### CODE REVIEW

**Comment by solonovamax** [comment]
What was the reason for deciding to merge these modules?

I have a few projects that use kds and/or kmem, but not klock, klogger, or korau. and, I would really prefer to not have to include those in my projects if I don't need them.

**Comment by soywiz** [comment]
> What was the reason for deciding to merge these modules?
> 
> I have a few projects that use kds and/or kmem, but not klock, klogger, or korau. and, I would really prefer to not have to include those in my projects if I don't need them.

Focus.

I have forked it before doing this: https://github.com/korlibs/korlibs4 . Community can contribute to that repo for those libs and keep releasing 4.x.y versions there and backport fixes and features from/to there.

**Comment by solonovamax** [comment]
I see. I understand that.

is there any way that (specifically) kds and kmem could still be maintained as separate modules, or no?

**Comment by soywiz** [comment]
Yes. The korlibs4 repository is the way to go for that.

**Pull request merged**
