### PR TITLE
Revert "Remove experimental wrapped klock variants (#1508)"

### PR DESCRIPTION
**Pull request by soywiz**
This reverts commit 982d8666ddb9fe91a75801a2b4c0f9f96132128b.

Would fix https://github.com/korlibs/korge/issues/1586

Let's figure out if people is still using it again.

### CODE REVIEW

**Comment by soywiz** [comment]
Hey folks 👋 https://github.com/korlibs-archive/klock/issues/108

@lamba92 @RomeuG are you still using this? I can add the wrapped versions again if it makes sense.

**Comment by RomeuG** [comment]
Hi @soywiz! Not anymore, in my case. Thank you for the heads up.

**Comment by soywiz** [comment]
In the end I'm going to merge it, just in case some people still uses this but didn't see this RFC so they can bump without losing functionality.

**Comment by dalewking** [comment]
My team is definitely still using this and it actually is preventing us from updating to latest version. BUT we will be migrating away from Klock over the next month so not that big of a deal.

**Comment by soywiz** [comment]
No worries. It was clear to me. But since I'm not sure how much people might be in the same situation, and it is something that can be done easily I think it might benefit other people. Eventually the idea is to use kotlinx.datetime and wrap around that. But in the meantime this can be a solution for those people.

**Pull request merged**
