### PR TITLE
Refactor bus package to it's own library.

### PR DESCRIPTION
**Pull request by Kietyo**
Context: My game has a dependency on the bus utils but not necessarily the Korge UI stuff. Refactoring the bus package to it's own library allows me to pull in the bus utils without needing to also pull in all of korge.

### CODE REVIEW

**Comment by soywiz** [comment]
Makes sense to separate, but the way to go here is kproject. Specially for small additions like a couple of classes dependencies.

kproject should be usable outside korge projects too.

You can fork this project:

https://github.com/korlibs/korge-kproject-template

then create a `korio-bus` folder with a kproject and make `example` use it. Then transfer it to the korlibs org.

another option is to create the `korio-bus` in the korlibs/korge-services repository and make a PR there.

Once any of those is done we can remove bus from this repo and update the README to include a link to it.

**Comment by Kietyo** [comment]
I would like to go with option 2 but not sure how that would work. Can you do it as an example so I can follow it for the future?

**Comment by soywiz** [comment]
@Kietyo 
Sent it also in the #contributors channel on discord, since this might take some time to process:
https://www.youtube.com/watch?v=JX4HxlsPF-E

**Comment by Kietyo** [comment]
Can you save that commit from the video example and share it with me?

TBH video is not all that useful and consumes too much time to view. Also my eyes have trouble with dark theme.

**Comment by soywiz** [comment]
Just duplicate this file:
https://github.com/korlibs/korge-services/blob/main/korge-i18n/kproject.yml

in anoter folder, ie. `korio-bus` and change the name inside the yaml to `korio-bus`.
Then add the relative path to korio-bus in the `example/deps.kproject.yml` https://github.com/korlibs/korge-services/blob/main/example/deps.kproject.yml

Open/refresh the `example` project inside intellij and you should be able to create src folders inside the example.

For troubleshooting, [invert your screen colors](https://www.minitool.com/news/windows-10-invert-colors.html) so dark becomes white, and check the video.

**Pull request closed without merging**
