### PR TITLE
Some renames and deprecations

### PR DESCRIPTION
**Pull request by Inego**

### CODE REVIEW

**Comment by Inego** [comment]
It seems the deprecation level should be WARNING...

**Comment by soywiz** [comment]
deprecate_replace_with

The cat you have in your avatar looks a lot to the cat I had for 18 years. What a beautiful nice animal :)



Thank you very much!

**Comment by Inego** [comment]
Haha, you seem to be a gentleman with a sense of humor! :D

**Comment by soywiz** [comment]
I really appreciate time spent on contributions, giving you a smile is the least I can try to do :)

**Pull request merged**
